//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Spy.ResourcesFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My_Spy.ResourcesFiles.ProgramStrings", typeof(ProgramStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        internal static string badpassword {
            get {
                return ResourceManager.GetString("badpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel remind?.
        /// </summary>
        internal static string Cancelremind {
            get {
                return ResourceManager.GetString("Cancelremind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want cancel remind?.
        /// </summary>
        internal static string Cancelremindtext {
            get {
                return ResourceManager.GetString("Cancelremindtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete this note?.
        /// </summary>
        internal static string DeleteNote {
            get {
                return ResourceManager.GetString("DeleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit note.
        /// </summary>
        internal static string EditNote {
            get {
                return ResourceManager.GetString("EditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is protected with password.
        /// </summary>
        internal static string IsProtected {
            get {
                return ResourceManager.GetString("IsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind.
        /// </summary>
        internal static string Remind {
            get {
                return ResourceManager.GetString("Remind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind date.
        /// </summary>
        internal static string RemindDate {
            get {
                return ResourceManager.GetString("RemindDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want send email with new password?.
        /// </summary>
        internal static string sendemail {
            get {
                return ResourceManager.GetString("sendemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        internal static string sendemailheader {
            get {
                return ResourceManager.GetString("sendemailheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
