#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Chat_Android.Resource", IsApplication=true)]

namespace Chat_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int off = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int send = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int smile1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int smile10 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int smile11 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int smile12 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Smile13 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Smile14 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Smile15 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Smile16 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int smile2 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int smile3 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int smile4 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int smile5 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int smile6 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int smile7 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int smile8 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int smile9 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int smiles = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int OnlineStatus = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int buttonlogin = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int editTextMessage = 2131165198;
			
			// aapt resource value: 0x7f070002
			public const int editTextpass = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int editTextuser = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int gridLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int imageButton1 = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int imageButton10 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int imageButton11 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int imageButton12 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int imageButton13 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int imageButton14 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int imageButton15 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int imageButton16 = 2131165215;
			
			// aapt resource value: 0x7f070011
			public const int imageButton2 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int imageButton3 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int imageButton4 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int imageButton5 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int imageButton6 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int imageButton7 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int imageButton8 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int imageButton9 = 2131165208;
			
			// aapt resource value: 0x7f07000b
			public const int imageButtonSend = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int imageViewStatus = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int imgButtonSmile = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayoutchat = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int radioButtonadmin = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int radioButtonuser = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int radioGroup1 = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int scrollviewchat = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int textViewStatus = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SmileLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
