//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgottenPassword.ResourcesFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProgramStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForgottenPassword.ResourcesFiles.ProgramStrings", typeof(ProgramStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t send next email. Wait 5 minutes..
        /// </summary>
        internal static string attempt {
            get {
                return ResourceManager.GetString("attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure code is bad.
        /// </summary>
        internal static string Badcode {
            get {
                return ResourceManager.GetString("Badcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sended to.
        /// </summary>
        internal static string EmailTo {
            get {
                return ResourceManager.GetString("EmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully. You may log in with new password..
        /// </summary>
        internal static string PassChange {
            get {
                return ResourceManager.GetString("PassChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        internal static string PassChangeHeader {
            get {
                return ResourceManager.GetString("PassChangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not equal.
        /// </summary>
        internal static string PasswordsNotEqual {
            get {
                return ResourceManager.GetString("PasswordsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want send email?.
        /// </summary>
        internal static string sendemail {
            get {
                return ResourceManager.GetString("sendemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        internal static string sendemailheader {
            get {
                return ResourceManager.GetString("sendemailheader", resourceCulture);
            }
        }
    }
}
